### ISSUE TITLE
error while running a single BRT model

### ISSUE THREAD

**Issue by elgabbas** [SEEG-Oxford/seegSDM#18] opened 2015-06-01 15:27 UTC
Hello All,
I have a problem with applying the tutorial on this line:
`brt <- runBRT(lis$data, 4:6, 1, covariates, gbm.coords = 2:3)`

I have this message:
![error](https://cloud.githubusercontent.com/assets/7375051/7916308/53743e00-0883-11e5-90b6-114f6c6f3ac0.jpg)

Thanks a lot,
Ahmed

**Comment by elgabbas** [comment] 2015-06-01 15:35
a different error appears while running this line: `model_list <- sfLapply(data_list, runBRT, 4:6, 1, covariates, gbm.coords = 2:3)`


``Error in checkForRemoteErrors(val) : ``
``  4 nodes produced errors; first error: 'predict.gbm' is not an exported object from 'namespace:gbm'``

**Comment by goldingn** [comment] 2015-07-30 13:43
Hi,

I've just tidied up the imports and dependencies for the package with 93bb8a26ad1044. Testing the new package (on linux), I can't replicate this error.

Hopefully that's because my changes fixed this, but would you mind re-installing seegSDM and seeing if it's fixed at your end?

Cheers, and sorry for the long delay in replying,
Nick

**Comment by elgabbas** [comment] 2015-07-30 14:20
Thanks Nick for your reply, but it still gives the same error message on my windows PC.

I've installed/updated the packages, and tried to re-run the tutorial without success. Installed versions are:
devtools: 1.8.0
seegSDM: 0.1-5
gbm: 2.1-06

Regards,
Ahmed

**Comment by goldingn** [comment] 2015-07-30 14:37
OK, thanks for testing this - and so quickly!

The new version of seegSDM with the fixes should be version 0.1-6, so it looks like something went wrong with the installation. You could try doing `remove.packages(seegSDM)` first and then installing again?

Similarly, the new version of `gbm` on CRAN is 2.1-1, it might be worth reinstalling that, though I don’t think it’s the source of the error.

Could you also let me know which version of `dismo` is installed? I think it was just a problem with declaring `dismo` as an import, but an old version of that package could apotentially be the cause. 

Cheers,
Nick

On 30 July 2015 at 15:20:33, Ahmed ElGabbas (notifications@github.com) wrote:

Thanks Nick for your reply, but it still gives the same error message on my windows PC.

I've installed/updated the packages, and tried to re-run the tutorial without success. Installed versions are:
devtools: 1.8.0
seegSDM: 0.1-5
gbm: 2.1-06

Regards,
Ahmed

**Comment by elgabbas** [comment] 2015-07-30 14:53
Thanks a lot for your immediate response.
It works now without getting the error!

However, the item ```coords``` of the ```brt``` object shows this error: 
```'$coords
Error in data.frame(Longitude = c("-6.15", "-4.65", " 2.65", "-5.35",  : 
  duplicate row.names:
```
Anyway, now I can keep going with the tutorial and see the rest of the function usage.

Cheers,
Ahmed

**Comment by goldingn** [comment] 2015-07-30 15:09
Great!

I'm not sure I understand where that error is arising.
I'll close this issue now as it seems to be fixed - if the new one is causing problems could you open an new issue with example code?

**Closed by goldingn** 2015-07-30 15:09 UTC
